### ISSUE TITLE
Can you release Pre-trained Model

### ISSUE THREAD

**Issue by puallee** [ljwztc/CLIP-Driven-Universal-Model#1]
Thanks for your code. Can you release the Pre-trained Model? Thanks

**Comment by ljwztc** [comment]
Thanks for your interest. As mentioned in README, you can download pre-trained model with `wget https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt`

**Comment by potpov** [comment]
Hello, 
Thank you for your incredible work!
The weights you provided are specific for the 3D network. 
Do you have a set of weights for the version with spatial dimension of 2? 
Thanks.

**Comment by ljwztc** [comment]
@potpov Hi potpov, thanks for your interest! Since 3d network is better for 3d data, we only train 3d network in this work. But you can replace the backbone in this work with anyother 2d networks.

**Comment by kretes** [comment]
Hello, I wanted to clarify one thing.
The `https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt` pretrained model is the one you've used as the starting point (together with CLIP embeddings) for your training, right? It's not the one that you trained in the end?

Have you released the final model weights as well?

**Comment by ljwztc** [comment]
> Hello, I wanted to clarify one thing. The `https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt` pretrained model is the one you've used as the starting point (together with CLIP embeddings) for your training, right? It's not the one that you trained in the end?
> 
> Have you released the final model weights as well?

Sure, you are right. 
We don't release final model weight yet, and plan to release the final model weights after reception

**Comment by GewelsJI** [comment]
Mark this issue and wait for the final model weights.

**Comment by MrGiovanni** [comment]
Hello @GewelsJI @kretes @potpov @puallee 

We just released the trained checkpoints of universal models. Please take a look at the README.

Best,

Zongwei
