### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Amshaker** [ljwztc/CLIP-Driven-Universal-Model#13]
Hi,

Thank you for your work.

Could you please provide more details regarding the training time?

Best regards,
Abdelrahman

**Comment by ljwztc** [comment]
We train the model in eight NVIDIA RTX A5000 cards for roughly 3~4 days.

**Comment by tangy5** [comment]
Training datasets are from multiple sources with more than 3,000 scans, the training takes ~400 epochs to converge, but depends on the GPU sources and tasks.
