### ISSUE TITLE
Question about Table 4

### ISSUE THREAD

**Issue by GewelsJI** [ljwztc/CLIP-Driven-Universal-Model#17]
Hi, @ljwztc @MrGiovanni 

Thanks for providing such a nice work. Kindly inquire two questions:

1. How to get testing images/labels of LiTS and KiTS?
2. How to evaluate the performance that reported in Table 4?

Best.

**Comment by ljwztc** [comment]
hi, thanks for your interest. 
1. We re-split the dataset as shown in `dataset/dataset_list`
2. After getting segmentation result, if there is no tumor prediction in health case, this case is true positive; if there is tumor prediction in health case, this one is false positive; so on and so forth. Based on this we can calculate sensitivity and specificity.

**Comment by GewelsJI** [comment]
big thanks for your quick reply.

**Comment by GewelsJI** [comment]
Hi @ljwztc 

Another question here is: what's the difference between AbdomenCT-1K and AbdomenCT 12organ? As for the latter one, I only find a [download link](https://github.com/JunMa11/AbdomenCT-1K#50-cases-with-13-annotated-organs-download-zenodo).

Could you provide more details?

Best.

**Comment by ljwztc** [comment]
The latter has 13 annotated organs and can be downloaded in [link](https://zenodo.org/record/7860267)
