### ISSUE TITLE
Table 3. Benchmark on BTCV validation dataset

### ISSUE THREAD

**Issue by cugwu** [ljwztc/CLIP-Driven-Universal-Model#18]
Hi, I would like to know in the benchmark in Table 3 of your paper, how many epochs did you use to train the different models? Since I notice that the performance of SwinUNETR is similar to the one in the official repository I suppose you used 5000 epochs for each model. Thanks in advance for the answer.

**Comment by ljwztc** [comment]
Hi, we fine-tune the universal model in the BTCV dataset in five cross validation way and report the result in average. The model is selected roughly in 300 epochs.

**Comment by cugwu** [comment]
Thanks, for the answer. And the other state-of-the-art methods on the tables are trained for how many epochs?

**Comment by ljwztc** [comment]
We don't re-implement them and simply copy the results.

**Comment by JiaxinZhuang** [comment]
Thanks for your work!! Can you provide the script as well as model weights to run the inference process of the Universal model for the BTCV validation dataset?

**Comment by AustinYuAo** [comment]
> 我们不会重新实现它们，只是复制结果。

Thanks for your work, can you provide a link to the results of the other  SOTA methods

**Comment by AustinYuAo** [comment]
> We don't re-implement them and simply copy the results.

Thanks for your work, can you provide a link to the results of the other  SOTA methods
