### ISSUE TITLE
Question about MSD dataset 10_07

### ISSUE THREAD

**Issue by SillenceHu** [ljwztc/CLIP-Driven-Universal-Model#20]
你好我想請問一下 utils.py , label_transfer.py的部分
您的分類有32種，我只需要Pancreas , Pancreas Tumor這兩種
我除了需要對編號進行修改還有需要針對哪些地方做更動嗎
NUM_CLASS
TEMPLATE
POST_TUMOR_DICT
MERGE_MAPPING_v1
MERGE_MAPPING_v2
TUMOR_ORGAN
函式裡的編號
例如organ 
post_pred_mask
dataset_index
organ_list

**Comment by ljwztc** [comment]
如果只需要訓練這兩個類別的話，可以按照正常的全監督方式訓練網絡，不需要按照partial label的方式訓練

**Comment by SillenceHu** [comment]
了解，謝謝
