### ISSUE TITLE
Confusion about embedding size

### ISSUE THREAD

**Issue by zhrthegreat** [ljwztc/CLIP-Driven-Universal-Model#21]
Hi, thank you for your excellent work.

I have a question about the size of the word embedding in the work. As the CLIP method given in the [link,](https://github.com/ljwztc/CLIP-Driven-Universal-Model/issues/9#issuecomment-1510766888) my embedding output is **n*512**, but your pre-trained embedding size is **n*256**. Is there something wrong with my input?

Thanks for any help.

**Comment by ljwztc** [comment]
the nn.Linear(text_to_vision) map 512 into 256
