### ISSUE TITLE
preprocessing for SwinUnetr backbone

### ISSUE THREAD

**Issue by cheliu-computation** [ljwztc/CLIP-Driven-Universal-Model#22]
Impressive work!

May I ask the image size you crop for swin-unetr backbone?
In the code, I find the default backbone is Unet and all crop size is 192, 192, 64, seems for 3DUnet, does it fit for swin-unter?
I have tried this size for Swin-unter following NVIDIA github repo, and it show some weird results and does not converge.

Would you mind provide the training code with swin-unter backbone or preprocessing code?

**Comment by ljwztc** [comment]
Thanks for your interest. We simply use the roi size with 96, 96, 96 for all backbones. This hyperparameter may not effect the convergence. 
All training and preprocessing code are uploaded in github. You should run the code with `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -W ignore -m torch.distributed.launch --nproc_per_node=8 --master_port=1234 train.py --dist True --backbone swinunetr --data_root_path DATA_ROOT_PATH --num_workers 12 --num_samples 4 --cache_dataset --cache_rate 0.6 --uniform_sample`

**Comment by GewelsJI** [comment]
@ljwztc 请问`--cache_dataset --cache_rate 0.6`去掉会对训练收敛有什么影响吗？这个加载速度太慢了

**Comment by ljwztc** [comment]
> 

canceling these two parameters would not effect the convergence. But it will slow down the training speed each epoch.
