### ISSUE TITLE
Confusion about dataset 02 and 03

### ISSUE THREAD

**Issue by kkk123698745** [ljwztc/CLIP-Driven-Universal-Model#23]
Hi，
Thanks for you great work!I'm a post graduate student trying to follow your work.I met some issue during my reproduction.
In dataset 02, I found that the ground truth regions in the dataset are too small, resulting in the model's dice,recall and precision are all zero in the test stage.
In dataset 03,there were two issues with the dataset: mismatch between the annotations and the actual liver positions, and some  CT images being completely black.
So,I wonder if I've missed something when I preprocessed the dataset which I obtained from the link given on the github.
Best,
Kevin Chen

**Comment by ljwztc** [comment]
Hi. Usually, pancreas is not small region and the dice can reach 80+. For dataset 03, we only use ct part. All ct images have corresponding label.

**Comment by kkk123698745** [comment]
> 
Thanks for reply！
So，followings are some examples I've met.For dataset02 the region takes small proportion in the whole 3D image.
![02dataset img53](https://github.com/kkk123698745/modifiedclip/blob/main/02dataset%20img53.png)
![02dataset label53](https://github.com/kkk123698745/modifiedclip/blob/main/02dataset%20label53.png)
Also,I took the CT part of the dataset 03,but the labels were not corresponded with the images. Is there someting wrong when i prepross the dataform(.dcm)?
![03dataset img5](https://github.com/kkk123698745/modifiedclip/blob/main/03dataset%20img5.png)
![03dataset label5](https://github.com/kkk123698745/modifiedclip/blob/main/03dataset%20label5.png)

**Comment by ljwztc** [comment]
Hi the multi-organ label for 02 can be downloaded here [link](https://zenodo.org/record/1169361). As for 03 problem, we use  `Orientationd ` [link](https://github.com/ljwztc/CLIP-Driven-Universal-Model/blob/main/dataset/dataloader.py#L230C13-L230C25) to ensure the direction. please double check.
