### ISSUE TITLE
Universal Pretrained Weight

### ISSUE THREAD

**Issue by zhi-xuan-chen** [ljwztc/CLIP-Driven-Universal-Model#24]
Hello, I want to check whether the pretrained weigt in this `https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt` link is Universal model pretrained weight?

**Comment by MrGiovanni** [comment]
Dear @zhi-xuan-chen 

We just released the trained checkpoints of universal models. Please refer to the README.

Best,

Zongwei
