### ISSUE TITLE
Code for tumor detection

### ISSUE THREAD

**Issue by zhi-xuan-chen** [ljwztc/CLIP-Driven-Universal-Model#28]
It seems the code in test.py is for segmentation. Can you release the code for tumor detection?

**Comment by ljwztc** [comment]
Thanks for your interest. The tumor detection in this work means identifying the tumor. Based on the segmentation results, the physician can know the location and shape of tumor. It is not the traditional concept of detection in computer vision (using such as fast RCNN).

**Comment by zhi-xuan-chen** [comment]
Thank you for your reply！Can you provide method to reproduce the results of tumor detection?

**Comment by ljwztc** [comment]
Yes, we can see whether there is the detected tumor after post-processing. If yes, this patient have related cancer.  If not, he/she is health.
