### ISSUE TITLE
doubts regarding training model only for Decathlon or Dataset: 10

### ISSUE THREAD

**Issue by nshah0812** [ljwztc/CLIP-Driven-Universal-Model#3]
Hi,

Thanks for interesting repo and paper
Could you guide me above the changes required to be done, if want to train model specifically for Decathlon dataset
Also, is there a way for sharing dataset in full, open datasets which are allowed to share

**Comment by ljwztc** [comment]
1. Download the Decathlon and arrange the dataset according to the dataset/dataset_list/PAOT.txt
2. Delete others lines except Decathlon related.
3. Follow the pipeline listed in README.

You have to apply for the download permission from corresponding institution before downloading these open datasets. I would like to share these dataset for your convenience but I can't.
