### ISSUE TITLE
Train and Test question

### ISSUE THREAD

**Issue by SillenceHu** [ljwztc/CLIP-Driven-Universal-Model#31]
你好
我在做訓練模型的時候用的是BTCV的dataset，
max_epoch=2000
store_num=50
warmup_epoch=100
最後再做test的時候出來的效果很差
Spleen: dice 0.0069, recall 0.9436, precision 0.0035.
Right Kidney: dice 0.0000, recall 0.0000, precision 0.0000.
Left Kidney: dice 0.0000, recall 0.0000, precision 0.0000.
Esophagus: dice 0.0000, recall 0.0000, precision 0.0000.
Liver: dice 0.0533, recall 0.9984, precision 0.0274.
Stomach: dice 0.0000, recall 0.0000, precision 0.0000.
Arota: dice 0.0000, recall 0.0000, precision nan.
Postcava: dice 0.0022, recall 0.9912, precision 0.0011.
Portal Vein and Splenic Vein: dice 0.0006, recall 1.0000, precision 0.0003.
Pancreas: dice 0.0000, recall 0.0000, precision 0.0000.
Right Adrenal Gland: dice 0.0000, recall 0.0000, precision nan.
Left Adrenal Gland: dice 0.0000, recall 0.0000, precision 0.0000.
case01_Multi-Atlas_Labeling/label/label0023| Spleen: 0.0069, Right Kidney: 0.0000, Left Kidney: 0.0000, Esophagus: 0.0000, Liver: 0.0533, Stomach: 0.0000, Arota: 0.0000, Postcava: 0.0022, Portal Vein and Splenic Vein: 0.0006, Pancreas: 0.0000, Right Adrenal Gland: 0.0000, Left Adrenal Gland: 0.0000,
ase01_Multi-Atlas_Labeling/label/label0023
想請教說怎麼會這樣

**Comment by ljwztc** [comment]
The recall for spleen, liver, postcava are all nearly 100% but other metrics are nearly 0%. It seems all ct are predicted as these three organs. Did you correctly process the label as instruction in README?

**Comment by wk100869** [comment]
Training Issues

Hello, may I ask how many epochs you have trained and the dice loss value at the final convergence

When I trained using three datasets (liver, kidney, and tumor), 04-LITS, 05KITS, and 10-3liver, I trained for 200 epochs. When I finally converged, the dice loss value was around 0.7. However, in the test set, the dice value range for liver and kidney was around 0.96, and the dice value for tumor was around 0.65. I don't understand why the dice loss value was so high during convergence. According to conventional understanding, when training convergence, dice predicted (1-0.7=) 0.3 correctly, The test results dice should also be very low, but the test set results are normal. Could you please answer them? Thank you very much

**Comment by Adoreeeeee** [comment]
Hello, I would like to ask some questions about training a new dataset. Can I reposition organ 1 to another organ? For example, the original organ 1 is the spleen, but I would like to define it as the left atrium.
