### ISSUE TITLE
Inference with pre-trained model?

### ISSUE THREAD

**Issue by fipeop** [ljwztc/CLIP-Driven-Universal-Model#32]
I am trying to run inference in an external dataset using the pre-trained weights. However, both test.py and pred_pseudo.py refer to resume checkpoint: ./out/Nvidia/old_fold0/aepoch_500.pth

Is this on purpose or are you planning to upload the checkpoint?

**Comment by kretes** [comment]
Have you downloaded checkpoints linked in https://github.com/ljwztc/CLIP-Driven-Universal-Model#model and put correct one at the path it's expecting it?

That's not an official answer, just what I think is required.

**Comment by ljwztc** [comment]
Hi, @kretes is right. Download the checkpoint from link and resume the pth using --resume. `./out/Nvidia/old_fold0/aepoch_500.pth` is just used in our server.

**Comment by fipeop** [comment]
Yes, it worked with the new checkpoint and some modification of the loading approach.
