### ISSUE TITLE
Question about AbdomenCT-1K

### ISSUE THREAD

**Issue by boxiangyun** [ljwztc/CLIP-Driven-Universal-Model#33]
Thanks for your great work.
I collect the dataset AbdomenCT-1K for "08_AbdomenCT-1K" and "13_AbdomenCT-12organ".
I can find 722 cases in [link](https://zenodo.org/record/5903037#.YfDOl-pBybh) and 50 cases in [link](https://zenodo.org/record/7860267). But there are 1k cases in your paper referred and Case_00001_0000~Case_01062_0000 for 08_AbdomenCT-1K in PAOT.txt.
So how to get 1k cases in 08_AbdomenCT-1K ?

Thanks.

**Comment by ljwztc** [comment]
We download the 08 from [link](https://docs.google.com/forms/d/e/1FAIpQLSeuZ3yanPc0E-SxvYD2ZX8eu-BKxxdQT5GQUpyzfUeK39ytow/viewform) in [official github](https://github.com/JunMa11/AbdomenCT-1K)

**Comment by boxiangyun** [comment]
Thanks, I find it!
