### ISSUE TITLE
question about implementation details

### ISSUE THREAD

**Issue by ShashankHuang** [ljwztc/CLIP-Driven-Universal-Model#34]
![image](https://github.com/ljwztc/CLIP-Driven-Universal-Model/assets/101397888/5a6368cd-a604-430f-9f6f-d33626227788)
Hi,
In your paper u said that u use batch size 6 with a patch size of 96 × 96 × 96 per device NVIDIA RTX A5000, which is with 24G video memory. But I use batch size 2 with a patch size of 96 × 96 × 96 per device NVIDIA RTX A5000, encountering cuda is out of memory. And I tried three backbones that were unet, swinunetr, unetpp, encountering the same issue.

**Comment by ljwztc** [comment]
There is a parameter `--num_samples` also effect the GPU consumption. So, the patch number in each card is `num_samples * batch_size`.
In our experience, we can train the model in 24G card with `2 * 1` or `1 * 2`.
