### ISSUE TITLE
01 BTCV dataset labels for testing subjects

### ISSUE THREAD

**Issue by Tianananana** [ljwztc/CLIP-Driven-Universal-Model#38]
Hi, from the dataset list in `PAOT.txt` I noticed that for BTCV dataset, you provided directories for the labels that corresponds to the testing subjects (img0061 to img0080). Can I check if these labels are generated using the `pred_pseudo.py` file? Or if there is another way to assess these labels? Thank you!

**Comment by ljwztc** [comment]
Hi you can download the unofficial GT for img0061 to img0080 in this [link](https://zenodo.org/record/1169361)

**Comment by Tianananana** [comment]
thank you!
