### ISSUE TITLE
How do you use the CLIP model？

### ISSUE THREAD

**Issue by yangsenwxy** [ljwztc/CLIP-Driven-Universal-Model#4]
Thank you very much for your work. I have some doubts. Where is your text input? The input of our model forwrad is an image. I did not find images of different parts and input different text features.

**Comment by ljwztc** [comment]
For computational efficiency, we pre-store the CLIP embedding in `https://github.com/ljwztc/CLIP-Driven-Universal-Model/blob/main/pretrained_weights/txt_encoding.pth` and load into model.
