### ISSUE TITLE
For the results of BTCV in the reproduction paper

### ISSUE THREAD

**Issue by Adoreeeeee** [ljwztc/CLIP-Driven-Universal-Model#44]
For the results of BTCV in the reproduction paper, I have some questions I want to ask, the 5-fold cross-verification method you mentioned, is it done five times with train.py and val.py? According to the classification in BTCV.json. Looking forward to your reply

**Comment by ljwztc** [comment]
Yes. We trained five different models according to the split in BTCV.json, but the code is not exactly same with train.py and val.py.

**Comment by ljwztc** [comment]
We conduct five-cross validation according to this file. More details please refer to https://github.com/ljwztc/CLIP-Driven-Universal-Model/issues/26

**Comment by AustinYuAo** [comment]
Thank you very much for your response. We have also submitted our training results to the official website, but we haven't received any results yet. Can I ask if you know how to obtain the segmentation results? I am eagerly looking forward to your reply.
