### ISSUE TITLE
Inference Issue with unet.pth

### ISSUE THREAD

**Issue by msds21024** [ljwztc/CLIP-Driven-Universal-Model#46]
I am facing this issue and havent been able to figure out the reason. Please guide.

  File "./clip/test.py", line 197, in main
    model.load_state_dict(store_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Universal_model:
	Unexpected key(s) in state_dict: "backbone.down_tr64.ops.0.conv1.weight", "backbone.down_tr64.ops.0.conv1.bias", "backbone.down_tr64.ops.0.bn1.weight", "backbone.down_tr64.ops.0.bn1.bias", "backbone.down_tr64.ops.0.bn1.running_mean", "backbone.down_tr64.ops.0.bn1.running_var", "backbone.down_tr64.ops.0.bn1.num_batches_tracked", "backbone.down_tr64.ops.1.conv1.weight", "backbone.down_tr64.ops.1.conv1.bias", "backbone.down_tr64.ops.1.bn1.weight", "backbone.down_tr64.ops.1.bn1.bias", "backbone.down_tr64.ops.1.bn1.running_mean", "backbone.down_tr64.ops.1.bn1.running_var", "backbone.down_tr64.ops.1.bn1.num_batches_tracked", "backbone.down_tr128.ops.0.conv1.weight", "backbone.down_tr128.ops.0.conv1.bias", "backbone.down_tr128.ops.0.bn1.weight", "backbone.down_tr128.ops.0.bn1.bias", "backbone.down_tr128.ops.0.bn1.running_mean", "backbone.down_tr128.ops.0.bn1.running_var", "backbone.down_tr128.ops.0.bn1.num_batches_tracked", "backbone.down_tr128.ops.1.conv1.weight", "backbone.down_tr128.ops.1.conv1.bias", "backbone.down_tr128.ops.1.bn1.weight", "backbone.down_tr128.ops.1.bn1.bias", "backbone.down_tr128.ops.1.bn1.running_mean", "backbone.down_tr128.ops.1.bn1.running_var", "backbone.down_tr128.ops.1.bn1.num_batches_tracked", "backbone.down_tr256.ops.0.conv1.weight", "backbone.down_tr256.ops.0.conv1.bias", "backbone.down_tr256.ops.0.bn1.weight", "backbone.down_tr256.ops.0.bn1.bias", "backbone.down_tr256.ops.0.bn1.running_mean", "backbone.down_tr256.ops.0.bn1.running_var", "backbone.down_tr256.ops.0.bn1.num_batches_tracked", "backbone.down_tr256.ops.1.conv1.weight", "backbone.down_tr256.ops.1.conv1.bias", "backbone.down_tr256.ops.1.bn1.weight", "backbone.down_tr256.ops.1.bn1.bias", "backbone.down_tr256.ops.1.bn1.running_mean", "backbone.down_tr256.ops.1.bn1.running_var", "backbone.down_tr256.ops.1.bn1.num_batches_tracked", "backbone.down_tr512.ops.0.conv1.weight", "backbone.down_tr512.ops.0.conv1.bias", "backbone.down_tr512.ops.0.bn1.weight", "backbone.down_tr512.ops.0.bn1.bias", "backbone.down_tr512.ops.0.bn1.running_mean", "backbone.down_tr512.ops.0.bn1.running_var", "backbone.down_tr512.ops.0.bn1.num_batches_tracked", "backbone.down_tr512.ops.1.conv1.weight", "backbone.down_tr512.ops.1.conv1.bias", "backbone.down_tr512.ops.1.bn1.weight", "backbone.down_tr512.ops.1.bn1.bias", "backbone.down_tr512.ops.1.bn1.running_mean", "backbone.down_tr512.ops.1.bn1.running_var", "backbone.down_tr512.ops.1.bn1.num_batches_tracked", "backbone.up_tr256.up_conv.weight", "backbone.up_tr256.up_conv.bias", "backbone.up_tr256.ops.0.conv1.weight", "backbone.up_tr256.ops.0.conv1.bias", "backbone.up_tr256.ops.0.bn1.weight", "backbone.up_tr256.ops.0.bn1.bias", "backbone.up_tr256.ops.0.bn1.running_mean", "backbone.up_tr256.ops.0.bn1.running_var", "backbone.up_tr256.ops.0.bn1.num_batches_tracked", "backbone.up_tr256.ops.1.conv1.weight", "backbone.up_tr256.ops.1.conv1.bias", "backbone.up_tr256.ops.1.bn1.weight", "backbone.up_tr256.ops.1.bn1.bias", "backbone.up_tr256.ops.1.bn1.running_mean", "backbone.up_tr256.ops.1.bn1.running_var", "backbone.up_tr256.ops.1.bn1.num_batches_tracked", "backbone.up_tr128.up_conv.weight", "backbone.up_tr128.up_conv.bias", "backbone.up_tr128.ops.0.conv1.weight", "backbone.up_tr128.ops.0.conv1.bias", "backbone.up_tr128.ops.0.bn1.weight", "backbone.up_tr128.ops.0.bn1.bias", "backbone.up_tr128.ops.0.bn1.running_mean", "backbone.up_tr128.ops.0.bn1.running_var", "backbone.up_tr128.ops.0.bn1.num_batches_tracked", "backbone.up_tr128.ops.1.conv1.weight", "backbone.up_tr128.ops.1.conv1.bias", "backbone.up_tr128.ops.1.bn1.weight", "backbone.up_tr128.ops.1.bn1.bias", "backbone.up_tr128.ops.1.bn1.running_mean", "backbone.up_tr128.ops.1.bn1.running_var", "backbone.up_tr128.ops.1.bn1.num_batches_tracked", "backbone.up_tr64.up_conv.weight", "backbone.up_tr64.up_conv.bias", "backbone.up_tr64.ops.0.conv1.weight", "backbone.up_tr64.ops.0.conv1.bias", "backbone.up_tr64.ops.0.bn1.weight", "backbone.up_tr64.ops.0.bn1.bias", "backbone.up_tr64.ops.0.bn1.running_mean", "backbone.up_tr64.ops.0.bn1.running_var", "backbone.up_tr64.ops.0.bn1.num_batches_tracked", "backbone.up_tr64.ops.1.conv1.weight", "backbone.up_tr64.ops.1.conv1.bias", "backbone.up_tr64.ops.1.bn1.weight", "backbone.up_tr64.ops.1.bn1.bias", "backbone.up_tr64.ops.1.bn1.running_mean", "backbone.up_tr64.ops.1.bn1.running_var", "backbone.up_tr64.ops.1.bn1.num_batches_tracked". 
	size mismatch for precls_conv.0.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
	size mismatch for precls_conv.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
	size mismatch for precls_conv.2.weight: copying a param with shape torch.Size([8, 64, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 48, 1, 1, 1]).
	size mismatch for GAP.0.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for GAP.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for GAP.3.weight: copying a param with shape torch.Size([256, 512, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 768, 1, 1, 1]).

**Comment by WEN-player** [comment]
hi, I face the same problem with you, have you solved it?

**Comment by msds21024** [comment]
Nope, still struggling with it

**Comment by WEN-player** [comment]
I changed the backbone in test.py  from swinunetr to unet in test.py, solved.
