### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by JcWang20** [ljwztc/CLIP-Driven-Universal-Model#49]
hello, I find your work very interesting, and I encountered some problems while reproducing it. I noticed that both the paper and the txt files in the datalist directory mention a total of 14 datasets, but it seems that there are only links to 12 datasets on this readme page. Also, the links for labels 08 and 12 are duplicated. Apart from one of your private datasets, should there be links for two more datasets? I would greatly appreciate your help in this matter.

**Comment by ljwztc** [comment]
08 and 12 are different subset of Abdomen1K. All links have been list in the README.
