### ISSUE TITLE
Can you share the model weights tested on the BTCV dataset？

### ISSUE THREAD

**Issue by min121101** [ljwztc/CLIP-Driven-Universal-Model#5]
Hello！
Thank you for your incredible work!
Can you share the model weights tested on the BTCV dataset？

**Comment by ljwztc** [comment]
Please stay tuned~ We would release the model weights later.

**Comment by ljwztc** [comment]
> Can you share the details of the dataset processing? I noticed that the official BTCV dataset has 83 items, but only 47 items in PAOT.txt.

As shown in official web `Under Institutional Review Board (IRB) supervision, 50 abdomen CT scans of were randomly selected from a combination of an ongoing colorectal cancer chemotherapy trial, and a retrospective ventral hernia study`, there are 50 CT scans and 3 of them are missing when we downloaded the data.

**Comment by min121101** [comment]
Hi, we ran out of memory while trying to reproduce your model. Did you use eight NVIDIA RTX A5000 during training?

**Comment by ljwztc** [comment]
> Hi, we ran out of memory while trying to reproduce your model. Did you use eight NVIDIA RTX A5000 during training?

Yes. You can decrease the `--batch_size` and `--num_samples` to save memory.

**Comment by MrGiovanni** [comment]
Dear @min121101 

We just released the trained checkpoints of universal models. Please take a look at the README.

Best,

Zongwei
