### ISSUE TITLE
Inference with trained model

### ISSUE THREAD

**Issue by loyee1123** [ljwztc/CLIP-Driven-Universal-Model#50]
Hi, This is a really good work.
I just wonder how to use a trained model to test my own dataset since I don't want to retrain the whole model.
Besides, Can the model accept a text imput such as the shape and the location of our aim object or just telling this is a xxx.

**Comment by ljwztc** [comment]
1. You can download the model weight ![here](https://www.dropbox.com/s/jdsodw2vemsy8sz/swinunetr.pth) and inference with your own dataset. 
2. Cannot.

**Comment by sharonlee12** [comment]
hello，can you successfully download it？I find that I cannot connect to https://www.dropbox.com/
