### ISSUE TITLE
training on parts of the datasets

### ISSUE THREAD

**Issue by sharonlee12** [ljwztc/CLIP-Driven-Universal-Model#52]
Hello, I want to train some datasets in PAOT.txt, such as 01_ Multi Atlas_ Labeling and 02_ TCIA_ Pancreas-CT and 03_ CHAOS, may I ask how to modify the label_transfer.py？The TRANSFER_LIST should be what?TRANSFER_LIST = ['01', '02', '03']?and do I need to modify the num_classes?if so,What should I change it to？
I tried to train on the BTCV dataset, but my diceloss and bce loss did not decrease, and the label_transfer.py is set like this
![settings](https://github.com/ljwztc/CLIP-Driven-Universal-Model/assets/120789038/1850ea8f-401b-4e7f-9adc-f6bd3a78ec47)

I hope to receive your guidance, thank you!

**Comment by sharonlee12** [comment]
I use with torch.no_grad() in training,I do this because of the"CUDA out of memory." question.Does it matter?
![22](https://github.com/ljwztc/CLIP-Driven-Universal-Model/assets/120789038/e015de2e-535f-4f40-adc9-34413ebaa776)

**Comment by ljwztc** [comment]
1. Yes. you can do the label_transfer step only with 01, 02, 03.
2. it matters. training require gradient. torch.no_grad() should be canceled during training

**Comment by sharonlee12** [comment]
> 1. Yes. you can do the label_transfer step only with 01, 02, 03.
> 2. it matters. training require gradient. torch.no_grad() should be canceled during training

Hello, nice to receive your reply! I have resolved the issue of cuda out of memory and used with torch. cuda. amp. autocast(),But I am training on BTCV, where diceloss oscillates continuously without decreasing, while celoss decreases. When I use my checkpoint to validate, the result is as follows:
Spleen: dice 0.0000, recall 0.0000, precision nan
Right Kidney: dice 0.0000, recall 0.0000, precision nan
Left Kidney: dice 0.0000, recall 0.0000, precision nan
Esophagus: dice 0.0000, recall 0.0000, precision nan
Liver: dice 0.0000, recall 0.0000, precision nan
Stomach: dice 0.0000, recall 0.0000, precision nan
Aorta: dice 0.0000, recall 0.0000, precision nan
Postcava: dice 0.0000, recall 0.0000, precision nan
Portal Vein and Splenic Vein: dice 0.0000, recall 0.0000, precision nan
Pancreas: dice 0.0000, recall 0.0000, precision nan
Right Adrenal Gland: dice 0.0000, recall 0.0000, precision nan
Left Adrenal Gland: dice 0.0000, recall 0.0000, precision nan
case01_Multi-Atlas_Labeling/label/label0035| Spleen: 0.0000, Right Kidney: 0.0000, Left Kidney: 0.0000, Eso
phagus: 0.0000, Liver: 0.0000, Stomach: 0.0000, Aorta: 0.0000, Postcava: 0.0000, Portal Vein and Splenic Ve
in: 0.0000, Pancreas: 0.0000, Right Adrenal Gland: 0.0000, Left Adrenal Gland: 0.0000,
Have you ever encountered a similar problem?
I hope to receive your reply, thank you!
Here is codes for training：










``  def train(args, train_loader, model, optimizer, loss_seg_DICE, loss_seg_CE):
    model.train()
    loss_bce_ave = 0
    loss_dice_ave = 0
    epoch_iterator = tqdm(
        train_loader, desc="Training (X / X Steps) (loss=X.X)", dynamic_ncols=True
    )
    for step, batch in enumerate(epoch_iterator):
        x, y, name = batch["image"].to(args.device), batch["post_label"].float().to(args.device), batch['name']
        torch.cuda.empty_cache()
        with torch.cuda.amp.autocast():
          logit_map = model(x)
        torch.cuda.empty_cache()

        term_seg_Dice = loss_seg_DICE.forward(logit_map, y, name, TEMPLATE)
        term_seg_BCE = loss_seg_CE.forward(logit_map, y, name, TEMPLATE)
        loss = term_seg_BCE + term_seg_Dice
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        epoch_iterator.set_description(
            "Epoch=%d: Training (%d / %d Steps) (dice_loss=%2.5f, bce_loss=%2.5f)" % (
                args.epoch, step, len(train_loader), term_seg_Dice.item(), term_seg_BCE.item())
        )
        loss_bce_ave += term_seg_BCE.item()
        loss_dice_ave += term_seg_Dice.item()
        torch.cuda.empty_cache()
    print('Epoch=%d: ave_dice_loss=%2.5f, ave_bce_loss=%2.5f' % (args.epoch, loss_dice_ave/len(epoch_iterator), loss_bce_ave/len(epoch_iterator)))
    
    return loss_dice_ave/len(epoch_iterator), loss_bce_ave/len(epoch_iterator)``

**Comment by sharonlee12** [comment]
Here is the picture of training loss:
![image](https://github.com/ljwztc/CLIP-Driven-Universal-Model/assets/120789038/0f2f4cb6-d17d-4c69-8a5f-c30fa4374bc6)
![image](https://github.com/ljwztc/CLIP-Driven-Universal-Model/assets/120789038/c4ed2cc3-d75b-4124-a51f-93d92fb2c1aa)

**Comment by Adoreeeeee** [comment]
> Hello, I want to train some datasets in PAOT.txt, such as 01_ Multi Atlas_ Labeling and 02_ TCIA_ Pancreas-CT and 03_ CHAOS, may I ask how to modify the label_transfer.py？The TRANSFER_LIST should be what?TRANSFER_LIST = ['01', '02', '03']?and do I need to modify the num_classes?if so,What should I change it to？ I tried to train on the BTCV dataset, but my diceloss and bce loss did not decrease, and the label_transfer.py is set like this ![settings](https://private-user-images.githubusercontent.com/120789038/289341475-1850ea8f-401b-4e7f-9adc-f6bd3a78ec47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzE3MTksIm5iZiI6MTcwMzIzMTQxOSwicGF0aCI6Ii8xMjA3ODkwMzgvMjg5MzQxNDc1LTE4NTBlYThmLTQwMWItNGU3Zi05YWRjLWY2YmQzYTc4ZWM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNzUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTBlODgzZGQ2ODA2MmZkMGM0MDU2ZjgxNTZjODJkN2EyYWNkYmYxMzE5NDNlODI0OTNhOGExMWZiNWQ4MTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FPOkBp08dLgxwuQFQ7Jdbd_OIa5MdWFMul-FMrFE7P4)
> 
> I hope to receive your guidance, thank you!

Hello! I'm having a similar issue with you. I used a new backbone and a new dataset. I did everything I could, but when I trained, diceloss=1 and bceloss dropped.

**Comment by ljwztc** [comment]
I haven't met this before. Usually, the bce loss will decrease to less than 0.01 and the dice loss will decrease to roughly 0.7

**Comment by sharonlee12** [comment]
> I haven't met this before. Usually, the bce loss will decrease to less than 0.01 and the dice loss will decrease to roughly 0.7

Hello, may I ask if you trained on PAOT.txt? That is to say, for all datasets, I wonder if this is due to the small size of the dataset, as I only train on BTCV. Thank you!

**Comment by 13772846495** [comment]
> Hello, I want to train some datasets in PAOT.txt, such as 01_ Multi Atlas_ Labeling and 02_ TCIA_ Pancreas-CT and 03_ CHAOS, may I ask how to modify the label_transfer.py？The TRANSFER_LIST should be what?TRANSFER_LIST = ['01', '02', '03']?and do I need to modify the num_classes?if so,What should I change it to？ I tried to train on the BTCV dataset, but my diceloss and bce loss did not decrease, and the label_transfer.py is set like this ![settings](https://private-user-images.githubusercontent.com/120789038/289341475-1850ea8f-401b-4e7f-9adc-f6bd3a78ec47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTU1OTQsIm5iZiI6MTcxMTU5NTI5NCwicGF0aCI6Ii8xMjA3ODkwMzgvMjg5MzQxNDc1LTE4NTBlYThmLTQwMWItNGU3Zi05YWRjLWY2YmQzYTc4ZWM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMzA4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2MyNGQ5NzIwMTE5NGZiYzE1MTVhZmEzODQ2NWZhMDQ0MmJjOTFkMGVlMDJjMmRhZWI1NTQ3NzBkM2RiZjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jLErDkY61XIMj2vNwERbcC2PwMFb6jzsZKMGVT3MUtA)
> 
> I hope to receive your guidance, thank you!
Hello, Sorry to disturb you amidst your busy schedule. I heard that you also train with small datasets. I'm training with the BTCV dataset as well. However, during testing, I encountered a RuntimeError: Error(s) in loading state_dict for Universal_model: Unexpected key(s) in state_dict: "", "0.weight", "0.bias", "2.weight", "2.bias", "3.weight", "3.bias", "weight", "bias". I'm not sure how to resolve this. Have you encountered it before?

**Comment by 13772846495** [comment]
Hello, Sorry to disturb you amidst your busy schedule. I heard that you also train with small datasets. I'm training with the BTCV dataset as well. However, during testing, I encountered a RuntimeError: Error(s) in loading state_dict for Universal_model: Unexpected key(s) in state_dict: "", "0.weight", "0.bias", "2.weight", "2.bias", "3.weight", "3.bias", "weight", "bias". I'm not sure how to resolve this. Have you encountered it before?

> > I haven't met this before. Usually, the bce loss will decrease to less than 0.01 and the dice loss will decrease to roughly 0.7
> 
> Hello, may I ask if you trained on PAOT.txt? That is to say, for all datasets, I wonder if this is due to the small size of the dataset, as I only train on BTCV. Thank you!

**Comment by sharonlee12** [comment]
> > I haven't met this before. Usually, the bce loss will decrease to less than 0.01 and the dice loss will decrease to roughly 0.7
> 
> Hello, may I ask if you trained on PAOT.txt? That is to say, for all datasets, I wonder if this is due to the small size of the dataset, as I only train on BTCV. Thank you!

No，I just train on BTCV，because PAOT.xt has a large dataset size

**Comment by ljwztc** [comment]
1. As for dice loss: The bug in the dice loss calculation has been addressed at [this link](https://github.com/ljwztc/CLIP-Driven-Universal-Model/blob/49715510829946f09f8330bd3a6e7b02e9fd51de/utils/loss.py#L20). Consequently, we can now observe an expected decrease in the dice loss.
2. As for convergence: The convergence of this model may require a substantial dataset, although it is not necessarily the sole contributing factor.
