### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by JcWang20** [ljwztc/CLIP-Driven-Universal-Model#59]
First of all, thank you for your nice work
When I trained the full data set according to the training configuration provided by your codebase and the batchsize of 6 mentioned in the paper, the training process got errors out of memory. When I used the batchsize of 1, I observed during training on a100 that the minimum 10g of video memory fluctuated to 50g at the maximum, and when I set numsamples to 2, the maximum fluctuated to 30g. All other Settings are the default Settings in this codebase.
However, I noticed that your paper mentioned that you used NVIDIA RTX A5000 8 cards, and the batchsize was 6 per gpu. Why did the graphics memory occupy 50g when my batchszie was 1? Is there any setting that was not enabled?
I noticed that the RTX A5000 is only 24GB
In addition, I can only enable the cache rate to be 0.1. When my rate is larger, errors will be reported during the data recording process:
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 183979 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 183973) of binary:  /usr/bin/python3
I set num_workers to 0, but the error is still the same without more detailed error, from 2 to 16, the error is the same, may I ask what is the reason for this, have you ever encountered it

**Comment by ljwztc** [comment]
1. Both `args.num_samples` and `args.batch_size` would effect the batch size.  The batch size of 6 in paper is a typo. We did not use such large number. 
2. The fluctuation of GPU memory is large since some dataset would predict large number of organ, which would occupy large GPU memory.
3. If your machine can not cache such large data, you can turn down the cache rate.

**Comment by JcWang20** [comment]
Thank you for your reply,
1. Therefore, the batchsize of your original experiment setting is 1. If I use 6 calories for training, I can basically reproduce your results, is my understanding correct?
2. In addition, is it my understanding that cache data only affects the speed but not the effect of the final model? So whether I adjust the rate or do not use cache will not affect the segmentation performance of the model?
By the way I would appreciate it if you can get your contact information and consult me in time @ljwztc

**Comment by ljwztc** [comment]
1. yes
2. yes
you can contact me through email in my personal webpage
