### ISSUE TITLE
05_KiTS which ground truth labels?

### ISSUE THREAD

**Issue by aashusri** [ljwztc/CLIP-Driven-Universal-Model#6]
Hi, thanks for the great work! 

Could you please tell which labels you used for the Kits dataset. In the ground truth, there are three different aggregations for the ground truths:

```
aggregated_AND_seg.nii.gz
aggregated_MAJ_seg.nii.gz
aggregated_OR_seg.nii.gz
```

**Comment by ljwztc** [comment]
The OR one is used

**Comment by aashusri** [comment]
Perfect, thanks!
