### ISSUE TITLE
problems during training

### ISSUE THREAD

**Issue by sharonlee12** [ljwztc/CLIP-Driven-Universal-Model#60]
hello！I trained on the LITS dataset,and during training,dice loss and bce loss can be reduced during training, 
but during the test, the results are  all 0: 
(epoch 500):
Liver: dice 0.0000, recall 0.0000, precision 0.0000.
Liver Tumor: dice 0.0000, recall 0.0000, precision nan.
case04_LiTS/label/liver_1| Liver: 0.0000, Liver Tumor: 0.0000, Case04_LITS /label/liver_1| liver: 0.0000, liver tumor: 0.0000,
At the beginning (epoch 50), the result is
Liver: dice 0.1749, recall 0.4666, precision 0.1077.
Liver Tumor: dice 0.0032, recall 1.0000, precision 0.0016.
I am confused about this, what is the possible reason? I look forward to your reply, thank you!

**Comment by sharonlee12** [comment]
In addition, the results with the pre-trained model you provided are normal：
Liver: dice 0.9786, recall 0.9776, precision 0.9796.
Liver Tumor: dice 0.8918, recall 0.9217, precision 0.8640.
case04_LiTS/label/liver_10| Liver: 0.9786, Liver Tumor: 0.8918,

**Comment by Adoreeeeee** [comment]
I'm having the same issue as you. I think it could be that the model is too big and needs enough data to train. A single small data set cannot satisfy parameter learning.

**Comment by ljwztc** [comment]
The convergence of this model may require a substantial dataset, although it is not necessarily the sole contributing factor.
