### ISSUE TITLE
Extract vision embeddings 

### ISSUE THREAD

**Issue by hep-raidium** [ljwztc/CLIP-Driven-Universal-Model#61]
Hi there, 
First, thank you for sharing your work!

I would like to extract one embedding for each image from the vision encoder.
I didn't succeed in doing so, have you ever done it ? If yes, do you have a few hints / code to share ? 

Thx!!

**Comment by ljwztc** [comment]
After obtaining the feature map, you can scale up to the input size. Then you can find the feature vector for each category with ground truth.
