### ISSUE TITLE
data request

### ISSUE THREAD

**Issue by ruida** [ljwztc/CLIP-Driven-Universal-Model#64]
In PAOT_train.txt and PAOT_test.txt, could you upload the corresponding label files on Google Drive?  I can't find those label files in the original data released.  Thanks.   --Ruida

PAOT_train.txt:
01_Multi-Atlas_Labeling/img/img0061.nii.gz	01_Multi-Atlas_Labeling/label/label0061.nii.gz
01_Multi-Atlas_Labeling/img/img0062.nii.gz	01_Multi-Atlas_Labeling/label/label0062.nii.gz
01_Multi-Atlas_Labeling/img/img0063.nii.gz	01_Multi-Atlas_Labeling/label/label0063.nii.gz
01_Multi-Atlas_Labeling/img/img0064.nii.gz	01_Multi-Atlas_Labeling/label/label0064.nii.gz
01_Multi-Atlas_Labeling/img/img0065.nii.gz	01_Multi-Atlas_Labeling/label/label0065.nii.gz
01_Multi-Atlas_Labeling/img/img0067.nii.gz	01_Multi-Atlas_Labeling/label/label0067.nii.gz
01_Multi-Atlas_Labeling/img/img0069.nii.gz	01_Multi-Atlas_Labeling/label/label0069.nii.gz
01_Multi-Atlas_Labeling/img/img0070.nii.gz	01_Multi-Atlas_Labeling/label/label0070.nii.gz
01_Multi-Atlas_Labeling/img/img0075.nii.gz	01_Multi-Atlas_Labeling/label/label0075.nii.gz
01_Multi-Atlas_Labeling/img/img0079.nii.gz	01_Multi-Atlas_Labeling/label/label0079.nii.gz
01_Multi-Atlas_Labeling/img/img0080.nii.gz	01_Multi-Atlas_Labeling/label/label0080.nii.gz

PAOT_test.txt:
01_Multi-Atlas_Labeling/img/img0068.nii.gz      01_Multi-Atlas_Labeling/label/label0068.nii.gz
01_Multi-Atlas_Labeling/img/img0074.nii.gz      01_Multi-Atlas_Labeling/label/label0074.nii.gz
01_Multi-Atlas_Labeling/img/img0076.nii.gz      01_Multi-Atlas_Labeling/label/label0076.nii.gz
01_Multi-Atlas_Labeling/img/img0078.nii.gz      01_Multi-Atlas_Labeling/label/label0078.nii.gz

**Comment by ljwztc** [comment]
Sure. The postlabel file can be accessed in this [link](https://portland-my.sharepoint.com/:u:/g/personal/jliu288-c_my_cityu_edu_hk/EX04Ilv4zh1Lm_HB0wnpaykB4Slef043RVWhX3lN05gylw?e=qG0DOS)

**Comment by ruida** [comment]
Thanks.  Could you upload the label files in .nii.gz format?

**Comment by ljwztc** [comment]
you can download the nii.gz format in this [link](https://zenodo.org/records/1169361)

**Comment by ruida** [comment]
Just get it.  Thanks much!
