### ISSUE TITLE
how many epochs did you train

### ISSUE THREAD

**Issue by sharonlee12** [ljwztc/CLIP-Driven-Universal-Model#67]
I am hoping to know how many epochs you trained？I see in the train.py is 2000，It is too large I see

**Comment by studyhard2024** [comment]
How many epochs did you train? I tried to run the code with my dataset, and ran 500 epochs. However, the dice score is too low. Did you meet this situation as me?

**Comment by JcWang20** [comment]
> How many epochs did you train? I tried to run the code with my dataset, and ran 500 epochs. However, the dice score is too low. Did you meet this situation as me?

which dataset do you use， i use all the data for training and ran500epochs with 8 a100, and can not reach the result in paper

**Comment by ljwztc** [comment]
The bug in the dice loss calculation has been addressed at [this link](https://github.com/ljwztc/CLIP-Driven-Universal-Model/blob/49715510829946f09f8330bd3a6e7b02e9fd51de/utils/loss.py#L20). Consequently, we can now observe an expected decrease in the dice loss.
