### ISSUE TITLE
Inquiring about Memory Usage and Device Utilization during Training

### ISSUE THREAD

**Issue by xuehe-dec** [ljwztc/CLIP-Driven-Universal-Model#68]
I am currently experiencing out-of-memory (OOM) issues during the training process, and I'm seeking assistance to understand the memory usage and device utilization during the training of your project.

Details:

Problem Description:
I am encountering out-of-memory errors during training, and I would like to understand the memory requirements of the training process.

Questions:

Could you provide information on the approximate memory usage of your training script?
What devices are utilized during the training process? (e.g., GPU type and memory)

**Comment by ljwztc** [comment]
For training, a minimum of 24GB of memory is required for each GPU. Using multiple GPUs is recommended. The detailed training information and setup we utilized can be found in the "Implementation Details" section of our paper.
