### ISSUE TITLE
the code of generalizability, transferability, and extensibility

### ISSUE THREAD

**Issue by studyhard2024** [ljwztc/CLIP-Driven-Universal-Model#72]
Thanks for the great jobs. Can you share the code of generalizability, transferability, and extensibility? I'd be very gratitude.

**Comment by ljwztc** [comment]
Generalizability code can be seen in the `Direct Inference in Your OWN CT scans` part in README. Transferability is a standard transfer learning process. You can leverage any existing transfer learning code, as long as you correctly load the provided model weights. Extensibility can be seen [here](https://github.com/MrGiovanni/ContinualLearning).
