### ISSUE TITLE
Question on dataset 12: 

### ISSUE THREAD

**Issue by vuquocan1987** [ljwztc/CLIP-Driven-Universal-Model#76]
Hi,

I have a question regarding the organ labels in the AbdomenCT-1K 12 organs dataset. On the dataset page, it mentions that there are 13 labeled organs. Could you please clarify how the 12-organ dataset was derived? Additionally, the labeling order on the dataset page doesn't seem to match the order in your code. 
Thank you!

**Comment by ljwztc** [comment]
You can find [here](https://zenodo.org/records/7860267).
