### ISSUE TITLE
How to get BTCV Testing Data Label?

### ISSUE THREAD

**Issue by Mentholatum** [ljwztc/CLIP-Driven-Universal-Model#89]
Impressive work! I noticed in the `datase_list/PAOT.txt` file, the `01_Multi-Atlas_Labeling` includes labels for `img0061.nii.gz` to `img0080.nii.gz`. However, I was informed by the BTCV official website that these are test set data and the labels are not available. May I ask how you obtained these labels? If you have the original labels, could you please send them to my email (mentholatum07@gmail.com)?

**Comment by ljwztc** [comment]
#38  you can find here

**Comment by Mentholatum** [comment]
> #38 you can find here

Thanks a lot！
