### ISSUE TITLE
Confuse about word embedding

### ISSUE THREAD

**Issue by Zac2049** [ljwztc/CLIP-Driven-Universal-Model#9]
I try to customize this code for my own datasets. But I found the `word_embedding` is fixed by load `txt_encoding.pth` in the train file. 
Is it right? For my own customization, should I modify this .pth file? And is there a good way to train it or produce it? And in the test file, I met the similar question.

Thanks for any help.

**Comment by kretes** [comment]
From my understanding of the codebase - you can either read in the `txt_encoding.pth` or let the word embedding be a random, trainable one.
To do that you need to instantiate UniversalModel with `encoding = 'rand_embedding'` and then do not load pretrained text embeddings.

This has an effect in https://github.com/ljwztc/CLIP-Driven-Universal-Model/blob/main/model/Universal_model.py#L117

I understood that the initial values of `txt_encoding.pth` were obtained from the CLIP model for specific prompts (with specific organ names) - so if you want your own, you should produce your own in a similar way.

**Comment by ljwztc** [comment]
Thanks @kretes for elaborate explain. 
@Zac2049 Sure, the clip embedding is generated with text encode in https://github.com/openai/CLIP. If you want to customize your own dataset, you should modify the .pth file. Here is an example for generate clip embedding.
```
import os
import clip
import torch

ORGAN_NAME = ['Spleen', 'Right Kidney', 'Left Kidney', 'Gall Bladder', 'Esophagus', 
                'Liver', 'Stomach', 'Arota', 'Postcava', 'Portal Vein and Splenic Vein',
                'Pancreas', 'Right Adrenal Gland', 'Left Adrenal Gland', 'Duodenum', 'Hepatic Vessel',
                'Right Lung', 'Left Lung', 'Colon', 'Intestine', 'Rectum', 
                'Bladder', 'Prostate', 'Left Head of Femur', 'Right Head of Femur', 'Celiac Truck',
                'Kidney Tumor', 'Liver Tumor', 'Pancreas Tumor', 'Hepatic Vessel Tumor', 'Lung Tumor', 
                'Colon Tumor', 'Kidney Cyst']

# Load the model
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load('ViT-B/32', device)


text_inputs = torch.cat([clip.tokenize(f'A computerized tomography of a {item}') for item in ORGAN_NAME]).to(device)

# Calculate text embedding features
with torch.no_grad():
    text_features = model.encode_text(text_inputs)
    print(text_features.shape, text_features.dtype)
    torch.save(text_features, 'txt_encoding.pth')
```

**Comment by Zac2049** [comment]
Thanks for your help!! @ljwztc @kretes 
But I have a another problem. I got some organs which not include in the `ORGAN_NAME` list, but It is not unnecessary to finetune CLIP because the 'ViT-B/32' is good enough to identify ''A computerized tomography of a {new_item}'', right?

**Comment by Zac2049** [comment]
Thanks~
