### ISSUE TITLE
Questions about label_transfer.py

### ISSUE THREAD

**Issue by Mentholatum** [ljwztc/CLIP-Driven-Universal-Model#90]
Dear Author,

I am very impressed with your work! When I was reading your paper published in Medical Image Analysis, I noticed that Table 1 introduces information about the datasets used. In the BTCV (01_Multi-Atlas_Labeling) dataset, the target is stated as 13. However, on `line 59` of the `label_transfer.py` , the template declaration ranges from 1 to 14. Does this mean that the 14 templates include a background template? If so, in Table 2 of the paper, which discusses the unification of the label taxonomy, the 14th label representing the duodenum is not present in the BTCV dataset. I am looking forward to your response and appreciate your time!

Best regards.

**Comment by ljwztc** [comment]
you can find the label we used for training [here](https://zenodo.org/records/1169361).
