### ISSUE TITLE
inconsistency in TEMPLATE dictionary in label_transfer.py

### ISSUE THREAD

**Issue by arghavan99** [ljwztc/CLIP-Driven-Universal-Model#91]
Hello, 
thanks for the great work, 

In dataset `'02'` which is the Pancreas-CT dataset, seems like only one organ is labeled. But in the `TEMPLATE` dictionary inside `label_transfer.py` the entry for dataset `'02'` is like this: `'02': [1,0,3,4,5,6,7,0,0,0,11,0,0,14]`
Could you please explain what it indicates? 

Thanks

**Comment by ljwztc** [comment]
you can find the label file with multi-organ annotation [here](https://zenodo.org/records/1169361).

**Comment by arghavan99** [comment]
Thank you so much!
